/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package table;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BHARATHA
 */
public class TableView extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    public TableView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        genderLbl = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        maritialLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        genderCombox = new javax.swing.JComboBox<>();
        ageTxt = new javax.swing.JTextField();
        singleCbox = new javax.swing.JCheckBox();
        marriedCbox = new javax.swing.JCheckBox();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Details");
        setLocation(new java.awt.Point(410, 185));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLbl.setText("Name :");
        jPanel1.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 32, -1, -1));

        genderLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genderLbl.setText("Gender :");
        jPanel1.add(genderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        ageLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageLbl.setText("Age :");
        jPanel1.add(ageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        maritialLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maritialLbl.setText("Maritial :");
        jPanel1.add(maritialLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, -1));

        genderCombox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genderCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Gender>", "Male", "Female" }));
        jPanel1.add(genderCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        ageTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, -1));

        singleCbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        singleCbox.setText("Single");
        jPanel1.add(singleCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        marriedCbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        marriedCbox.setText("Married");
        jPanel1.add(marriedCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 80, -1));

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Age", "Maritial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 130));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:

        if (nameTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Name");
        } else if (genderCombox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please Select Gender");
        } else if (ageTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Age");
        } else if (!(singleCbox.isSelected() || marriedCbox.isSelected())) {
            JOptionPane.showMessageDialog(this, "Please Select Status");
        } else if (singleCbox.isSelected() && marriedCbox.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please Select one Status");
        } else {

            String name = nameTxt.getText();
            String gender = genderCombox.getSelectedItem().toString();
            String maritial = null;
            boolean b = false;

            if (singleCbox.isSelected() ^ marriedCbox.isSelected()) {

                if (singleCbox.isSelected()) {
                    maritial = "Single";
                } else {
                    maritial = "Married";
                }
            }

            try {
                int age = Integer.parseInt(ageTxt.getText());

                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                dtm.addRow(new Object[]{name, gender, age, maritial});

            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Enter Valid Age");
                b = true;
            }

            if (b == false) {
                nameTxt.setText("");
                ageTxt.setText("");
                genderCombox.setSelectedIndex(0);
                singleCbox.setSelected(false);
                marriedCbox.setSelected(false);
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is empty, nothing to remove");
        } else {
            int[] i = jTable1.getSelectedRows();
            if (i.length > 0) {
                int response = JOptionPane.showConfirmDialog(this, "Do you want to remove selected person(s)", "Remove", JOptionPane.YES_NO_OPTION);
                if (response == 0) {
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    for (int j = 0; j < i.length; j++) {
                        int k = i[j];
                        dtm.removeRow(k - j);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Select a person to remove");
            }
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TableView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> genderCombox;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel maritialLbl;
    private javax.swing.JCheckBox marriedCbox;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton removeBtn;
    private javax.swing.JCheckBox singleCbox;
    // End of variables declaration//GEN-END:variables
}
